/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Basic: typeof import('./src/components/block/basic/index.vue')['default']
    BasicCard: typeof import('./src/components/card/basicCard/index.vue')['default']
    CompareInsurance: typeof import('./src/components/block/compareInsurance/index.vue')['default']
    CompareIRR: typeof import('./src/components/tableCell/compareIRR/index.vue')['default']
    ComparePrice: typeof import('./src/components/tableCell/comparePrice/index.vue')['default']
    CompareRecord: typeof import('./src/components/block/compareRecord/index.vue')['default']
    CompareSingleInterest: typeof import('./src/components/tableCell/compareSingleInterest/index.vue')['default']
    CompareWavlerInsurance: typeof import('./src/components/block/compareWavlerInsurance/index.vue')['default']
    InsuranceProductByCompare: typeof import('./src/components/card/insuranceProductByCompare/index.vue')['default']
    Login: typeof import('./src/components/form/login/index.vue')['default']
    MulpowerTag: typeof import('./src/components/tag/mulpowerTag/index.vue')['default']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    SelectandcompareInsurance: typeof import('./src/components/list/selectandcompareInsurance/index.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
    WavlerinsuranceDetail: typeof import('./src/components/block/wavlerinsuranceDetail/index.vue')['default']
  }
}
